support multiple ssh keys
Azure/terraform-azurerm-compute pull request #147
Opened 2020-10-06 20:07 UTC by sudoapt-getclean

I needed support for multiple keys, the cleanest way to do that seemed to me to just change the existing var.ssh_keys to a list

An alternative implementation that would be backwards compatible would be to introduce a separate variable ssh_keys and merge them in a local. let me know if you prefer that.

2020-10-12 06:24 UTC, yupwei68 commented
Hi @sudoapt-getclean , thanks for opening this PR. 
1. I prefer not to break the users by add an extra variable "ssh_keys"
2. Please enabled this feature into fixture/test/main.tf and test if it works when it's assigned and if it works when it's not assigned
3. Please add this feature into the example of README.md

2020-10-13 19:12 UTC, CrowderKroger requested changes

2020-10-13 19:44 UTC, sudoapt-getclean commented on variables.tf
> +variable "os_disk_size_gb" {
Yes, that is a mess-up on my side,.. I'm also moving master forward to accommodate my project. I should have created this PR from a stable branch.

2020-10-13 21:59 UTC, sudoapt-getclean commented on README.md
> +2 - Ubuntu 18.04 Server VMs using `vm_os_publisher`, `vm_os_offer` and `vm_os_sku` which is configured with:
This is an unrelated fix because 18.04 is actually used n the example below

2020-11-19 09:20 UTC, yupwei68 approved these changes
Thanks! LGTM!

2020-11-19 09:20 UTC, merged