Bring support for marketplace images use with VMs
Azure/terraform-azurerm-compute pull request #180
Opened 2022-07-06 14:19 UTC by hightoxicity

Fixes #000 

Changes proposed in the pull request:

Exchanged today with Alex from Azure support and we were unable to use marketplace image with this module, troubleshooting generated VM, what missed were the plan section of _azurerm_virtual_machine_

This PR allow users to use such type of images.

2022-11-15 05:46 UTC, lonegunmanb requested changes
Thanks @hightoxicity for opening this pr! Could we the following `precondition` for these `azurerm_virtual_machine` resources?:

```hcl
lifecycle {
    precondition {
      condition    = !var.is_marketplace_image || (var.vm_os_offer != null && var.vm_os_publisher != null && var.vm_os_sku != null)
      error_message = "`var.vm_os_offer`, `vm_os_publisher` and `var.vm_os_sku` are required when `var.is_marketplace_image` is `true`."
    }
  }
```

As the [document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#plan) shows, when we declare this `plan` block, we need to ensure that all three arguments are not `null`.

2022-11-15 05:46 UTC, lonegunmanb commented on variables.tf
> +  default     = false
Could we add `nullable = false` here?

2022-11-18 21:34 UTC, hightoxicity commented
@lonegunmanb I added requested changes to the PR rebasing on master and adding 2 commits on top of rebased branch (initial commit and additional input checks)

2022-11-22 07:19 UTC, lonegunmanb requested changes
Thanks @hightoxicity for updating the pr, however we've got an issue raised by our CI pipeline. Would you please follow the instructions in [readme](https://github.com/Azure/terraform-azurerm-compute/blob/master/README.md#pre-commit--pr-check--test) file to help us by running the pre-commit and pr-check command then try again? Thanks for your cooperation!

2022-11-25 00:21 UTC, lonegunmanb requested changes
Thanks @hightoxicity for update this pr! We've refactor the master branch, now we have some conflicts for this pull request, would you please merge you branch with the latest master branch, and check the [document](https://github.com/Azure/terraform-azurerm-compute/#pre-commit--pr-check--test) before you commit? Thanks for your understanding!

2022-11-25 00:21 UTC, lonegunmanb commented on main.tf
> +  lifecycle {
Thanks @hightoxicity for update this pr! Would you please move this block to the end of this resource block since we've enforced a code style linting rule? Apology for the inconvenience and thanks for your understanding!

2022-11-25 00:21 UTC, lonegunmanb commented on main.tf
> +  dynamic "plan" {
We're sorting all arguments and nested blocks by the following order:

1. Required arguments in alphabet order
2. Optional arguments in alphabet order
3. Required nested blocks in alphabet order
4. Optional nested blocks in alphabet order

Would you please help us by reordering you newly added blocks? Thanks!

2022-11-25 00:21 UTC, lonegunmanb commented on variables.tf
> +variable "is_marketplace_image" {
We're sorting variables by the following order:

1. Required （without default value） variables in alphabet order
2. Optional variables in alphabet order

Please help us by reordering your newly added variable, thanks!

2022-11-25 00:21 UTC, lonegunmanb commented on main.tf
> +  lifecycle {
Should we add the same `precondition` block to windows vm resource too?

2022-11-29 06:04 UTC, lonegunmanb commented
I'm closing this pr because the feature has been implemented by #209 . Thanks @hightoxicity for your contribution!

2022-11-29 06:04 UTC, closed without merging