Allow custom OS disk size
Azure/terraform-azurerm-compute pull request #183
Opened 2022-10-19 14:53 UTC by yatzek

Fixes #172

2022-10-19 14:54 UTC, yatzek commented
@microsoft-github-policy-service agree

2022-11-15 03:59 UTC, lonegunmanb requested changes
Thanks @yatzek for opening this pr! We've added a CI pipeline to this repo so would you please rebase your branch to the latest master branch? Thanks!

Btw, I've some questions for your pr.

2022-11-15 03:59 UTC, lonegunmanb commented on variables.tf
> +  default     = 30
Could we use `null` as default value since as [provider source code](https://github.com/hashicorp/terraform-provider-azurerm/blob/bfa19d0852b812f4c954178971190c251c738381/internal/services/legacy/virtual_machine_resource.go#L373-L378) shows, `disk_size_gb` argument has no default value, this variable with default value might introduce breaking changes to our users if they upgrade the module version and ignore the Terraform plan file.

2022-11-15 03:59 UTC, lonegunmanb commented on variables.tf
> +  description = "Storage os data disk size."
Could we copy the description from [the resource's document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#disk_size_gb)?

2022-11-15 03:59 UTC, lonegunmanb commented on variables.tf
> +variable "storage_os_disk_size_gb" {
We assign the `storage_os_disk_size_gb` to `storage_data_disk.disk_size_gb`, are we sure that the disk is os disk?

2022-11-15 09:17 UTC, yatzek commented on variables.tf
> +  default     = 30
Done.

2022-11-15 09:17 UTC, yatzek commented on variables.tf
> +  description = "Storage os data disk size."
Done.

2022-11-15 09:44 UTC, yatzek commented on variables.tf
> +variable "storage_os_disk_size_gb" {
_storage_os_disk_size_gb_ is only assigned to _storage_os_disk_ blocks, one for linux and one for windows:
 
LINUX:
![image](https://user-images.githubusercontent.com/82675711/201885982-d7a19c53-4f84-4fab-ab26-f59bec029b31.png)

WINDOWS:
![image](https://user-images.githubusercontent.com/82675711/201886153-e955c393-8f26-4b54-8b51-d6908984bf85.png)

2022-11-15 10:57 UTC, lonegunmanb commented on variables.tf
> +variable "storage_os_disk_size_gb" {
Thanks for your justification, LGTM now. I'll run the checks and tests. Again, thanks for your contribution!

2022-11-15 11:00 UTC, lonegunmanb requested changes
@yatzek we've got an issue when the pipeline executed the `pr-check` job, would you please read this [section](https://github.com/Azure/terraform-azurerm-compute#pre-commit--pr-check--test) and help us by running `make pre-commit` job, then verify your commit with `make pr-check`? Thanks for your understanding!

2022-11-15 13:39 UTC, lonegunmanb approved these changes
Thanks @yatzek, LGTM!

2022-11-15 13:40 UTC, merged