Optionally create an availability set
Azure/terraform-azurerm-compute pull request #228
Opened 2023-01-31 05:39 UTC by DatsloJRel

## Describe your changes
Add variable to optionally create an availability set

## Checklist before requesting a review
- [X] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [X] I have executed pre-commit on my machine
- [X] I have passed pr-check on my machine

Thanks for your cooperation!

2023-02-01 02:41 UTC, jiaweitao001 reviewed
Thank for the PR @DatsloJRel ! Overall looks good. Just as few comments to address.

2023-02-01 02:41 UTC, jiaweitao001 commented on variables.tf
> +variable "enable_availability_set" {
According to our new codex, I suggest renaming this variable to `availability_set_enabled`.

2023-02-01 02:41 UTC, jiaweitao001 commented on variables.tf
> +  default     = true
To ensure this variable is not `null`. I suggest we would better add `nullable = false` here.

2023-02-01 02:41 UTC, jiaweitao001 commented on main.tf
> +  availability_set_id           = (var.enable_availability_set && (var.zone == null)) ? azurerm_availability_set.vm[0].id : null
Same.

2023-02-01 02:41 UTC, jiaweitao001 commented on main.tf
> +  availability_set_id              = (var.enable_availability_set && (var.zone == null)) ? azurerm_availability_set.vm[0].id : null
Maybe this looks simpler?

```
availability_set_id = try(azurerm_availability_set.vm[0].id, null)
```

2023-02-01 05:25 UTC, DatsloJRel commented on variables.tf
> +variable "enable_availability_set" {
Agreed.  Changed in latest commit.

2023-02-01 05:49 UTC, lonegunmanb requested changes
Thanks @DatsloJRel for the update, only one tiny description issue remains.

2023-02-01 05:49 UTC, lonegunmanb commented on variables.tf
> +  description = "(Optional) Enable or Disable availability set.  Default is true (enabled)."
Would the following description be better?:

```hcl
description = "(Optional) Enable or Disable availability set.  Default is `true` (enabled)."
```

2023-02-02 14:53 UTC, DatsloJRel reviewed
I have made the requested change.

2023-02-02 14:56 UTC, DatsloJRel commented on variables.tf
> +  description = "(Optional) Enable or Disable availability set.  Default is true (enabled)."
I have made the suggested change.

2023-02-06 07:14 UTC, lonegunmanb approved these changes
Thanks @DatsloJRel, LGTM! 🚀

2023-02-06 07:15 UTC, merged